### ISSUE TITLE
Design feedback

### ISSUE THREAD

**Issue by ptrslr** [m-barnas/langusta3-web#1]
Celý ten dizajn na mňa pôsobí trochu zastaralo, v dnešnej dobe je veľmi populárny "flat" design a tie inner shadows a rounded corners (napr. v hlavičke a pätičke) nepôsobia veľmi dobre.

To papierové pozadie sa mi tiež veľmi nepáči, radšej by som tam žiadne pozadie nedával a ak už hej, tak niečo veľmi jemné a nenápadné (viď https://www.transparenttextures.com/ a https://www.toptal.com/designers/subtlepatterns/ )

Vyhľadávacie tlačidlo by malo byť napravo od inputu, taký je UX pattern, ľudia sú tak navyknutý. Budú asi potrebné aj nejaké filtre, tak to by bolo asi tiež potrebné navrhnúť. 

Skús to možno spraviť viac "minimalistické", nech je dominantný práve ten input na vyhľadávanie (inšpiroval by som sa google) a tých grafických efektov radšej použiť menej ako viac. 

Použil by som asi iné písmo, asi skôr bezpätkové písmo, prípadne nejakú kombináciu bezpätkového a pätkového. Viď https://fonts.google.com/

Možno by bolo fajn pajcnúť [Material](https://material.io/guidelines/material-design/introduction.html) dizajn od google, ako už raz bolo spomínané. Je tam toho veľa, ale keď si rozklikneš to menu vľavo, máš tam **komponenty**, v **style** máš farby a ikonky, atď...
https://github.com/material-components/material-components-web

**Inšpirácia:**
- Google
- [Airbnb](https://airbnb.com/)
- [Skyscanner](https://www.skyscanner.net/)
- [Foursquare](https://foursquare.com/)
- [Yelp](https://www.yelp.com)

Ak vás napadajú nejaké weby, ktoré majú dobré vyhľadávanie alebo sa vám z nejakého dôvodu páčia, sem s nimi.

**Články na UX:**
- https://www.fastcodesign.com/3054616/the-3-commandments-of-great-ux-design
- http://www.uxmatters.com/mt/archives/2009/09/best-practices-for-designing-faceted-search-filters.php

**Comment by ptrslr** [comment]
Prípadne teraz ani nerieš veľmi ako to vyzerá (farby, pozadie atď), ale práve to UX. Teda spraviť skôr nejaké wireframes, ako budú tie komponenty rozložené a ako sa to bude správať. Ako sa budú dáta vypisovať a filtrovať.

**Comment by m-barnas** [comment]
Predpokladám, že Martina chcela dať len nejaký prvý nástrel, či ide dobrým smerom, čiže to, že tam chýba funkcionalita je pochopiteľné.

Jej úlohou je pripraviť návrh užívateľského rozhrania, čo vyžaduje dôkladný prehľad o systéme a jeho funkciách. Naša aplikácia má umožňovať rozumnú prácu s aktuálne spracovanými dátami. Jej primárny cieľ nieje niečo nejak niekde vyhľadávať (aj keď vyhľadávanie tomu predchádza), ale spracovať vstup od užívateľa (slovo/veta/text/regex) a vykresliť k tomu štatistiky, zaujímavosti, fakty.

Ako primárnu funkciu aplikácie navrhujem analýzu slova/vety/textu/skupiny slov, zoskupenej pomocou regex. Dohodneme sa na max. počte znakov, ktorý spracujeme v rámci jedného dotazu. Hlavná komponenta danej stránky bude teda `<textarea>`, nie `<input type="search">`.

Tlačítko má byť samozrejme na pravej strane, aby to malo prirodzený priebeh, píšem zľava-doprava -> vpravo ma čaká tlačítko, ak vôbec nejaké bude, môžeme to urobiť real-time, viď [Google Translator](https://translate.google.com/?hl=sk#en/sk/wefrg). Vysvetlivka pod `<textarea>` v znení "Napíš hľadaný výraz a stlač tlačítko" nieje potrebná. Ako sa hovorí, UI je ako vtip, ak je dobré nepotrebuje vysvetlenie.

Po zadaní textu sa ku každému slovu zobrazia informácie, ktoré vieme poskytnúť, napr. vzor, pád, číslo, neurčitok, atď. Každý vzor bude odkaz `<a>` a po kliknutí naň si budem môcť zobraziť nejaké zaujímavé fakty, ktoré si o ňom uchovávame, napr. počet slov, ktoré sa podľa neho skloňujú a pod. Ku každému slovu sa taktiež zobrazí tlačítko s funkciou _Nahlásiť chybu_. 

Takto by som mohol pokračovať do nekonečna, preto navrhujem osobné stretnutie.

**Predmet stretnutia:**

- informačná architektúra
- sumarizácia funkcionality

**Odporúčam sa predtým pozrieť na dáta, ktoré sú k dispozícii na** [slovnik](https://github.com/marxsk/slovnik).

Vygenerovať sa dajú z [langusta3](https://github.com/marxsk/langusta3), pomocou:

> java -cp dist/Langusta3.jar langusta3.cz.AsaTest patterns-k1.xml k1.txt

Čo sa týka material design, navrhujem na štýl [Volar](http://switcher.freshface.net/?theme=volar) (samozrejme nie single-page), čo zahrňuje:

**písmo:** [Lato](https://fonts.google.com/specimen/Lato) v kombinácii s [Open Sans](https://fonts.google.com/specimen/Open+Sans)

**farby:** biele pozadie + cca 4 ďalšie farby, ktoré sú príjemne zladené

**moderný design:** minimalizmus, full-width, ikony namiesto textu, ...

**floating labels:** [demo](https://www.google.cz/search?q=floating+labels+gif&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj045WIycrTAhWDOBoKHUHrArgQ_AUICigB&biw=1366&bih=648#imgrc=rSYwJjxO74ZPyM:) (Volar má trošku iné no mám napísaný kód aj pre variantu z dema)

Stojí za všimnutie:

**responzívnosť:** [Bootstrap 4](https://v4-alpha.getbootstrap.com/getting-started/introduction/)

**smooth scrolling:** [smoothscroll-for-websites](https://github.com/galambalazs/smoothscroll-for-websites) 

A mnoho, mnoho ďalšieho, viď demo.

**Comment by Allemis** [comment]
Ahoj, 

díky za připomínky a odkazy. Jak jsem psala, dělám něco podobného poprvé, tak se učím za pochodu :). Tu je náčrt wireframes: [https://wireframe.cc/pro/pp/ea4a9174783162](url), (_kdyby nešlo otevřít, zde je pdf_ - [morfo---Wireframe-cc.pdf](https://github.com/m-barnas/langusta3-web/files/966770/morfo---Wireframe-cc.pdf)). Je to zatím návrh, některá funkcionalita tedy chybí. Inspirace pro vyhledávání je z Google Translator. 

Pozn.: hledání podle vzoru není hotové a nemá zatím na horní liště záložku (bude přidána). Taky sem tam obrázky trošku skáčou - bude doladěno.

Ad funkcionalita - jak prosím chápete tyto poznámky od Gráce/lingvistek? 
1. kolik slov se skloňuje podle více vzorů? 
          --> uživatel zadá několik vzorů a aplikace vyhodí číslo? (bude nějaký omezený počet zadaných vzorů?) ... nebo se jedná o jedno číslo celkově?
2. ukaž slova, která končí na -a, aby se dal použít další filtr k těmto slovům 
          --> uživatel zadá konec slova, aplikace vrátí všechna slova, která tímto končí? 
          (... těch ale může být pro výpis opravdu hodně... nebo tomu rozumím špatně?)

Hezký zbytek dne. 
Martina

**Comment by m-barnas** [comment]
Čauec,

páči sa mi tvoj nápad, že sa rozšírené info zobrazí stále len o jednom slove, konkrétne o tom na ktoré klikneš, resp. prejdeš myšou. V mojom náčrte, ktorý som poslal na fb, by sa zobrazil celý zoznam a pre nejaký dlhý text by to bolo dosť nepraktické. Takže super.

Jedna vec, ktorá mi nesedí je, že v prípade Google Translate je v okne vľavo text v jednom jazyku, a v okne vpravo text v inom jazyku. To znamená, že obe okná majú svoje opodstatnenie. V našom prípade by bol v oboch oknách totožný text, s jedinou výnimkou, vpravo by boli slová, ktoré sa nachádzajú v našej databáze napr. farebne vyznačené a dalo by sa na nich kliknúť.

Otázka znie, či by sme si nevystačili s jedným oknom? Skúste sa vyjadriť, čo by bolo pohodlnejšie / priehľadnejšie / jednoduchšie. Užívateľ by prilepil text, a farebne by sa mu zvýraznili slová, ktoré máme spracované. Resp. stačilo by, ak by sa slovám, ktoré nie sú spracované trošku ubralo opacity. Taktiež by možno bolo vhodné si rozkliknúť aj slovo, ktoré nemáme spracované a navrhnúť zodpovednej osobe jeho skloňovanie, vzor, číslo atď. Alebo minimálne nejaká notifikácia, že má o to slovo užívateľ záujem. Lebo aktuálne sú spracované len najfrekventovanejšie slová českého jazyka.

Odpoveď na otázky:

1) U niektorých slov dochádza k prienikom, t.z. že sa skloňujú podľa viacerých vzorov, nie len podľa jedného. Užívateľ teda môže zadať viacero vzorov a zistiť si ktoré slová sa skloňujú v takejto kombinácii. Môže si taktiež zistiť číslo, koľko je takýchto slov. Môže si zistiť, koľko slov sa skloňuje len podľa jedného vzoru (výsledok bude celkové číslo), môže si zistiť koľko slov sa skloňuje podľa štyroch vzorov (výsledok bude celkové číslo), atď. Priama odpoveď na otázku je **koľko slov sa skloňuje podľa 2 a viac vzorov -> výsledok bude celkové číslo**.

2) Áno, môže ich byť hodne. To sa ešte musíme dohodnúť, či ich vieme nejak rozumne zobraziť, alebo ich zobraziť neumožníme, len k nim zobrazíme štatistiky. Náš cieľ je asi taký, že užívateľ zadá regex, všetky slová, ktoré končia na -a, a my by sme mu mali byť schopní povedať, či sú to skôr slová ženského rodu a skloňujú sa podľa vzoru _ŽENA_ alebo je väčšina týchto slov mužského rodu a skloňujú sa podľa vzoru _HRDINA_. T.z. výsledok takéhoto filtra by boli číselné zastúpenia pre jednotlivé vzory. 

Ako iste vidíte, funkcionalita bude rôznorodá, výsledok bude raz číslo, raz viacero čísel, raz analýza slova, vstup je raz regex, raz vzor, raz text a teda navrhnúť nejaké zmysluplné, jednoduché, intuitívne a pohodlné UI nebude až tak triviálne. Ešte sa vrátim k tomu, že by si pridala ďalšiu položku v menu. Ja by som tu funkcionalitu asi nerozťahoval do viacerých položiek v primárnom menu, ale inšpiroval by som sa google tlačítkom _Nastavenia_, resp. _Nástroje_. 

![image](https://cloud.githubusercontent.com/assets/26074376/25568861/c418c224-2e0c-11e7-8a0c-e27bf32eeb1c.png)

Tam by si užívateľ mal možnosť vybrať, či chce zadávať text / regex / vzor.

**Comment by Allemis** [comment]
Ahoj,

díky za odpovědi  a připomínky. Posílám novou verzi. Mrkněte prosím na ni. Nakonec jsem zvolila jen jednu vyhledávací tabulku (máš pravdu, ve dvou by to nevypadalo moc dobře), slova se budou zvýrazňovat průběžně, a přidala jsem další funkcionalitu. 

Inspirace Google tlačítkem nástroje podle mě moc nepůjde udělat, protože uživatel nechce vzor zadat, ale spíše jej vyhledat (a i výpisy budou vypadat trochu jinak). Zkusila jsem to takhto. 

Jedná se o čtyři různé druhy vyhledávání:
1. slovo/věta/regex 
2. vzory
3. slova končící na -a
4. počet slov ve vzorech

Co myslíte?

[wireframes.pdf](https://github.com/m-barnas/langusta3-web/files/975465/wireframes.pdf)

Marťa

**Comment by Allemis** [comment]
Nejnovější verze: 
[wireframes_11_05_2017.pdf](https://github.com/m-barnas/langusta3-web/files/993375/wireframes_11_05_2017.pdf). 

Bude to takto v pořádku nebo byste ještě něco poupravili?

Marťa
